# Sponsorship / Buy Me a Coffee
# Replace 'techbutton' with your actual Buy Me a Coffee username

# Buy Me a Coffee
custom: ['https://buymeacoffee.com/techbutton']

# Uncomment and add your usernames if you use these platforms:
# github: ['techbutton']
# patreon: techbutton
# ko_fi: techbutton
