services:
  # Arrmate - AI Media Library Companion
  # Natural language interface for Sonarr, Radarr, Lidarr, Plex, and more.
  arrmate:
    image: techbutton/arrmate:latest
    container_name: arrmate
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "starr", "all"]
    networks:
      - default
    ports:
      - "$ARRMATE_PORT:8000"
    volumes:
      - $DOCKERDIR/appdata/arrmate:/data
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

      # LLM provider (ollama | openai | anthropic)
      LLM_PROVIDER: ${LLM_PROVIDER:-ollama}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://ollama:11434}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-qwen2.5:7b}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      ANTHROPIC_MODEL: ${ANTHROPIC_MODEL:-claude-3-5-sonnet-20241022}

      # Media services — Arrmate auto-discovers these.
      # Use Docker service names as hostnames when on the same network.
      SONARR_URL: ${SONARR_URL:-}
      SONARR_API_KEY: ${SONARR_API_KEY:-}
      RADARR_URL: ${RADARR_URL:-}
      RADARR_API_KEY: ${RADARR_API_KEY:-}
      LIDARR_URL: ${LIDARR_URL:-}
      LIDARR_API_KEY: ${LIDARR_API_KEY:-}
      BAZARR_URL: ${BAZARR_URL:-}
      BAZARR_API_KEY: ${BAZARR_API_KEY:-}
      PLEX_URL: ${PLEX_URL:-}
      PLEX_TOKEN: ${PLEX_TOKEN:-}
      WHISPARR_URL: ${WHISPARR_URL:-}
      WHISPARR_API_KEY: ${WHISPARR_API_KEY:-}
      AUDIOBOOKSHELF_URL: ${AUDIOBOOKSHELF_URL:-}
      AUDIOBOOKSHELF_API_KEY: ${AUDIOBOOKSHELF_API_KEY:-}
      LAZYLIBRARIAN_URL: ${LAZYLIBRARIAN_URL:-}
      LAZYLIBRARIAN_API_KEY: ${LAZYLIBRARIAN_API_KEY:-}
      READARR_URL: ${READARR_URL:-}
      READARR_API_KEY: ${READARR_API_KEY:-}
      HUNTARR_URL: ${HUNTARR_URL:-}
      HUNTARR_API_KEY: ${HUNTARR_API_KEY:-}

      # Authentication (optional) — set up via Settings page in web UI
      SECRET_KEY: ${SECRET_KEY:-}
      AUTH_DATA_DIR: /data
    # DOCKER-LABELS-PLACEHOLDER
